#######################################################################
#   Copyright [2014] [Cisco Systems, Inc.]
# 
#   Licensed under the Apache License, Version 2.0 (the \"License\");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
# 
#       http://www.apache.org/licenses/LICENSE-2.0
# 
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an \"AS IS\" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#######################################################################

#
include $(CCSP_ROOT_DIR)/arch/ccsp_common.mk


target := $(ComponentBuildDir)/dmcli

source_files := $(call add_files_from_src,,'*.c')
obj_files := $(subst .c,.o,$(source_files))
obj_files := $(addprefix $(ComponentBuildDir)/, $(source_files:%.c=%.o))

-include $(obj_files:.o=.d)

$(target): $(obj_files)


#
#	Set up include directories
#
INCPATH += $(CCSP_COMMON_DIR)/source/util_api/ansc/AnscXmlDomParser
CFLAGS += $(addprefix -I, $(INCPATH))

#
#	Build target
#
all: $(target)


install:
	@echo "Installing CCSP DmCli Installables"
	@install -d -m 0755 $(CCSP_OUT_DIR)
	@cp -f $(target) $(CCSP_OUT_DIR)
	@ln -sf dmcli $(CCSP_OUT_DIR)/ccsp_bus_client_tool


.PHONY: all clean

clean:
	rm -Rf $(ComponentBuildDir)
    
LDFLAGS   += -lccsp_common
